-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 16:46:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Photo Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Photo Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Photo Database` DEFAULT CHARACTER SET utf8 ;
USE `Photo Database` ;

-- -----------------------------------------------------
-- Table `Photo Database`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photo Database`.`Users` (
  `UserID` VARCHAR(20) NOT NULL,
  `JoinedSince` DATETIME NOT NULL,
  PRIMARY KEY (`UserID`));


-- -----------------------------------------------------
-- Table `Photo Database`.`Albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photo Database`.`Albums` (
  `AlbumName` VARCHAR(50) NOT NULL,
  `CreatorUserID` VARCHAR(20) NOT NULL,
  `CreationDate` DATE NOT NULL,
  PRIMARY KEY (`AlbumName`),
  INDEX `CreatorUserID` (`CreatorUserID` ASC) VISIBLE,
  CONSTRAINT `CreatorUserID`
    FOREIGN KEY (`CreatorUserID`)
    REFERENCES `Photo Database`.`Users` (`UserID`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Photo Database`.`Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photo Database`.`Photos` (
  `Filename` VARCHAR(50) NOT NULL,
  `AlbumName` VARCHAR(50) NULL DEFAULT NULL,
  `DateTaken` DATETIME NOT NULL,
  `Filetype` VARCHAR(4) NOT NULL,
  `UploaderUserID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Filename`),
  INDEX `AlbumName` (`AlbumName` ASC) VISIBLE,
  INDEX `UploaderUserID_idx` (`UploaderUserID` ASC) VISIBLE,
  CONSTRAINT `PhotosAlbumName`
    FOREIGN KEY (`AlbumName`)
    REFERENCES `Photo Database`.`Albums` (`AlbumName`)
    ON UPDATE CASCADE,
  CONSTRAINT `UploaderUserID`
    FOREIGN KEY (`UploaderUserID`)
    REFERENCES `Photo Database`.`Users` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Photo Database`.`Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photo Database`.`Permissions` (
  `AccessUserID` VARCHAR(20) NOT NULL,
  `OwnerUserID` VARCHAR(20) NOT NULL,
  `PermissionAdded` DATETIME NOT NULL,
  `AlbumName` VARCHAR(50) NULL,
  `Filename` VARCHAR(50) NULL,
  INDEX `AccessUserID_idx` (`AccessUserID` ASC) VISIBLE,
  INDEX `OwnerUserID_idx` (`OwnerUserID` ASC) VISIBLE,
  INDEX `Filename_idx` (`Filename` ASC) VISIBLE,
  INDEX `AlbumName_idx` (`AlbumName` ASC) VISIBLE,
  CONSTRAINT `AccessUserID`
    FOREIGN KEY (`AccessUserID`)
    REFERENCES `Photo Database`.`Users` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `OwnerUserID`
    FOREIGN KEY (`OwnerUserID`)
    REFERENCES `Photo Database`.`Users` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `PermissionsFilename`
    FOREIGN KEY (`Filename`)
    REFERENCES `Photo Database`.`Photos` (`Filename`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `PermissionsAlbumName`
    FOREIGN KEY (`AlbumName`)
    REFERENCES `Photo Database`.`Albums` (`AlbumName`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Photo Database`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photo Database`.`Tags` (
  `Filename` VARCHAR(50) NOT NULL,
  `Tag` VARCHAR(20) NOT NULL,
  `TimeTagAdded` DATETIME NOT NULL,
  INDEX `Filename_idx` (`Filename` ASC) VISIBLE,
  CONSTRAINT `TagsFilename`
    FOREIGN KEY (`Filename`)
    REFERENCES `Photo Database`.`Photos` (`Filename`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
