-- MySQL Script generated by MySQL Workbench
-- Tue May  7 16:25:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Photo Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Users` (
  `UserID` VARCHAR(20) NOT NULL,
  `JoinedSince` DATETIME NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`UserID`));


-- -----------------------------------------------------
-- Table `Albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Albums` (
  `AlbumName` VARCHAR(50) NOT NULL,
  `CreatorUserID` VARCHAR(20) NOT NULL,
  `CreationDate` DATE NOT NULL,
  PRIMARY KEY (`AlbumName`),
  CONSTRAINT `CreatorUserID`
    FOREIGN KEY (`CreatorUserID`)
    REFERENCES `Users` (`UserID`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photos` (
  `Filename` VARCHAR(50) NOT NULL,
  `AlbumName` VARCHAR(50) NULL DEFAULT NULL,
  `DateTaken` DATETIME NOT NULL,
  `Filetype` VARCHAR(4) NOT NULL,
  `UploaderUserID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Filename`),
  CONSTRAINT `PhotosAlbumName`
    FOREIGN KEY (`AlbumName`)
    REFERENCES `Albums` (`AlbumName`)
    ON UPDATE CASCADE,
  CONSTRAINT `UploaderUserID`
    FOREIGN KEY (`UploaderUserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Permissions` (
  `AccessUserID` VARCHAR(20) NOT NULL,
  `OwnerUserID` VARCHAR(20) NOT NULL,
  `PermissionAdded` DATETIME NOT NULL,
  `AlbumName` VARCHAR(50) NULL DEFAULT NULL,
  `Filename` VARCHAR(50) NULL DEFAULT NULL,
  CONSTRAINT `AccessUserID`
    FOREIGN KEY (`AccessUserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `OwnerUserID`
    FOREIGN KEY (`OwnerUserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `PermissionsFilename`
    FOREIGN KEY (`Filename`)
    REFERENCES `Photos` (`Filename`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `PermissionsAlbumName`
    FOREIGN KEY (`AlbumName`)
    REFERENCES `Albums` (`AlbumName`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tags` (
  `Filename` VARCHAR(50) NOT NULL,
  `Tag` VARCHAR(20) NOT NULL,
  `TimeTagAdded` DATETIME NOT NULL,
  CONSTRAINT `TagsFilename`
    FOREIGN KEY (`Filename`)
    REFERENCES `Photos` (`Filename`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
